services:
    nest-app:
        build:
            context: .
            dockerfile: Dockerfile
        hostname: nest-app
        ports:
            - '4000:4000'
        depends_on:
            - auth-db
        networks:
            - backend
            - frontend

    auth-db:
        container_name: auth-db
        hostname: auth-db
        image: postgres:15.2
        restart: always
        environment:
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DB=${POSTGRES_DB}
        ports:
            - 5433:5432
        volumes:
            - postgres_data:/var/lib/postgresql/data
        networks:
            - backend
        healthcheck:
            test: ['CMD-SHELL', 'pg_isready -U root -d full-authorization']
            interval: 10s
            timeout: 5s
            retries: 5
            start_period: 10s

    auth-redis:
        hostname: auth-redis
        container_name: auth-redis
        image: redis:5.0
        restart: always
        # ports:
        #     - 6379:6379
        command: redis-server --requirepass ${REDIS_PASSWORD}
        volumes:
            - redis_data:/data
        networks:
            - backend

    redis-insight:
        image: redis/redisinsight:latest
        restart: always
        ports:
            - '5540:5540'
        volumes:
            - redis-insight:/data
        networks:
            - backend

volumes:
    postgres_data:
    redis_data:
    redis-insight:

networks:
    backend:
        external: true
    frontend:
        external: true
