services:
    auth-client:
        hostname: auth-client
        build:
            context: ./
            dockerfile: Dockerfile
        restart: always
        ports:
            - 3000:3000
        networks:
            - frontend

networks:
    frontend:
        external: true
